# https://eth-brownie.readthedocs.io/en/stable/config.html?highlight=dependencies
dependencies:
    # - <organization/repo>@<version>
    - smartcontractkit/chainlink@1.1.1
compiler:
    solc:
        remappings:
            - '@chainlink=smartcontractkit/chainlink@1.1.1'
dotenv: .env
wallets:
    from_key: ${PRIVATE_KEY}
networks:
    default: ganache-local # 默认是 development
    rinkeby:
        eth_usd_price_feed : "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
        verify: True
    mainnet-fork-dev:
        # https://docs.chain.link/docs/ethereum-addresses/
        eth_usd_price_feed : "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
        verify: False
    development:
        verify: False
    ganache-local:
        verify: False